name: Check and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    name: MoonBit Check & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MoonBit
        uses: moonbitlang/setup-moonbit@v1

      - name: MoonBit Check
        run: moon check --deny-warn

      - name: MoonBit Test
        run: moon test --deny-warn

      - name: MoonBit Format Check
        run: |
          moon fmt
          git diff --exit-code

      - name: MoonBit Info Check
        run: |
          moon info
          git diff --exit-code
